// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdrdahsirxmioklxamhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkcmRhaHNpcnhtaW9rbHhhbWhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTAzOTMsImV4cCI6MjA2MjEyNjM5M30.U3NpjeOr6BMpS1q1d4JuJOE0Gajn_3oZGqZ7e2h_eio";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);